name: Update Branch

on:
  repository_dispatch:
    types:
      - "test: on_push_main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: true
      - name: Readme Download Button Action
        env:
          REPO: "gitaction-trigger-test"
          COLOR: "black"
        run: |
          UPDATE=$(cat README.md | perl -0777 -pe 's#(${env.REPO})')
          echo "${UPDATE}" > README.md
      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push
        run: |
          git add .
          git commit -m "feat(submodules): update submodule"
          git push origin main
