name: Update Branch

on:
  repository_dispatch:
    types:
      - "test: on_push_main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: true
      - name: Update submodules
        run: |
          git submodule update --remote --recursive
      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and Push
        run: |
          git add .
          git commit -m "feat(submodules): update submodule"
          git push origin main
